# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import serverless_collections_pb2 as serverless__collections__pb2


class CollectionsServiceStub(object):
    """CollectionsService manages the collections of a qdrant serverless space.
    Unlike the qdrant server API, it exposes only a simplified configuration:
    the manager turns it into concrete qdrant settings, which are never
    exposed to the tenant.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/qdrant.serverless.CollectionsService/CreateCollection',
                request_serializer=serverless__collections__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=serverless__collections__pb2.CreateCollectionResponse.FromString,
                )
        self.DeleteCollection = channel.unary_unary(
                '/qdrant.serverless.CollectionsService/DeleteCollection',
                request_serializer=serverless__collections__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=serverless__collections__pb2.DeleteCollectionResponse.FromString,
                )
        self.GetCollection = channel.unary_unary(
                '/qdrant.serverless.CollectionsService/GetCollection',
                request_serializer=serverless__collections__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=serverless__collections__pb2.GetCollectionResponse.FromString,
                )
        self.ListCollections = channel.unary_unary(
                '/qdrant.serverless.CollectionsService/ListCollections',
                request_serializer=serverless__collections__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=serverless__collections__pb2.ListCollectionsResponse.FromString,
                )


class CollectionsServiceServicer(object):
    """CollectionsService manages the collections of a qdrant serverless space.
    Unlike the qdrant server API, it exposes only a simplified configuration:
    the manager turns it into concrete qdrant settings, which are never
    exposed to the tenant.
    """

    def CreateCollection(self, request, context):
        """Creates a collection with the given tenant-facing configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Deletes a collection and all of its data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Returns a single collection's configuration and stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Lists the caller's collections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=serverless__collections__pb2.CreateCollectionRequest.FromString,
                    response_serializer=serverless__collections__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=serverless__collections__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=serverless__collections__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=serverless__collections__pb2.GetCollectionRequest.FromString,
                    response_serializer=serverless__collections__pb2.GetCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=serverless__collections__pb2.ListCollectionsRequest.FromString,
                    response_serializer=serverless__collections__pb2.ListCollectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qdrant.serverless.CollectionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CollectionsService(object):
    """CollectionsService manages the collections of a qdrant serverless space.
    Unlike the qdrant server API, it exposes only a simplified configuration:
    the manager turns it into concrete qdrant settings, which are never
    exposed to the tenant.
    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qdrant.serverless.CollectionsService/CreateCollection',
            serverless__collections__pb2.CreateCollectionRequest.SerializeToString,
            serverless__collections__pb2.CreateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qdrant.serverless.CollectionsService/DeleteCollection',
            serverless__collections__pb2.DeleteCollectionRequest.SerializeToString,
            serverless__collections__pb2.DeleteCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qdrant.serverless.CollectionsService/GetCollection',
            serverless__collections__pb2.GetCollectionRequest.SerializeToString,
            serverless__collections__pb2.GetCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qdrant.serverless.CollectionsService/ListCollections',
            serverless__collections__pb2.ListCollectionsRequest.SerializeToString,
            serverless__collections__pb2.ListCollectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
