version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      version-updates:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        patterns: ["*"]
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      version-updates:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        patterns: ["*"]
    cooldown:
      default-days: 7
