[build]
  command = "mkdir -p public"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/*"
  to = "https://qdrant.tech/documentation/"
  status = 301
  force = true
