"""Regression tests for QdrantLocal portalocker file-handle cleanup.

Issue: https://github.com/qdrant/qdrant-client/issues/1234

When two :class:`QdrantClient` (or :class:`AsyncQdrantClient`) instances are
constructed against the same persistent directory, the second
constructor must raise immediately, leave *no* open file handle on the
half-built instance, and free that handle for the OS.

The original implementation in ``qdrant_client/local/qdrant_local.py``
opened the ``.lock`` file *before* attempting ``portalocker.lock(...)``
and re-raised ``RuntimeError`` from the ``LockException`` branch
without closing the file or resetting ``self._flock_file``. An
uncollectable handle leaked out of the constructor on every conflict.

These tests pin down the contract for both the synchronous
``QdrantLocal`` constructor and the autogenerated
``AsyncQdrantLocal`` constructor.
"""

from __future__ import annotations

import os
import tempfile

import pytest

from qdrant_client.local.async_qdrant_local import AsyncQdrantLocal
from qdrant_client.local.qdrant_local import QdrantLocal


def _holding_local(tmpdir: str) -> QdrantLocal:
    """Create a QdrantLocal that holds the .lock file open."""
    local = QdrantLocal(location=tmpdir)
    assert local._flock_file is not None
    assert not local._flock_file.closed
    return local


def test_lock_file_handle_attached_on_success() -> None:
    """Sanity check: on a healthy init the lock file is held open."""
    with tempfile.TemporaryDirectory() as tmpdir:
        local = _holding_local(tmpdir)
        try:
            lock_path = os.path.join(tmpdir, ".lock")
            assert os.path.exists(lock_path)
            assert local._flock_file is not None
            assert not local._flock_file.closed
        finally:
            local.close()


def test_constructor_raises_on_lock_conflict() -> None:
    """The losing constructor raises RuntimeError mentioning the location."""
    with tempfile.TemporaryDirectory() as tmpdir:
        holding = _holding_local(tmpdir)
        try:
            with pytest.raises(Exception) as excinfo:
                QdrantLocal(location=tmpdir)
            assert "already accessed by another instance" in str(excinfo.value)
        finally:
            holding.close()


@pytest.mark.xfail(
    reason=(
        "Regression for #1234: on the raising path the file handle "
        "opened in _load() must be closed and self._flock_file reset "
        "to None, so no descriptor leaks out of the constructor. The "
        "fix is keyed off the exception branch in _load()."
    ),
    strict=True,
)
def test_load_releases_flock_file_on_lock_exception() -> None:
    """Drive ``_load`` directly so we can inspect the half-built
    instance after the exception.

    Currently master opens ``.lock`` *before* attempting
    ``portalocker.lock``, so when the lock is held elsewhere the
    ``LockException`` re-raises as ``RuntimeError`` while
    ``self._flock_file`` still points to an open file descriptor.
    The fix should close the handle and reset the attribute.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        holding = _holding_local(tmpdir)
        try:
            loser = QdrantLocal.__new__(QdrantLocal)
            loser.force_disable_check_same_thread = False
            loser.location = tmpdir
            loser.persistent = True
            loser.collections = {}
            loser.aliases = {}
            loser._flock_file = None
            loser._closed = False

            with pytest.raises(Exception) as excinfo:
                loser._load()

            assert "already accessed by another instance" in str(excinfo.value)
            assert loser._flock_file is None
            assert (
                loser._flock_file is None
                or loser._flock_file.closed
            ), "the file handle leaked out of _load()"
        finally:
            holding.close()


@pytest.mark.xfail(
    reason=(
        "Regression for #1234: AsyncQdrantLocal mirrors QdrantLocal. "
        "Same fix expected in the autogenerated file."
    ),
    strict=True,
)
def test_load_releases_flock_file_on_lock_exception_async() -> None:
    """Mirror the sync test against the autogenerated async client."""
    with tempfile.TemporaryDirectory() as tmpdir:
        holding = _holding_local(tmpdir)
        try:
            loser = AsyncQdrantLocal.__new__(AsyncQdrantLocal)
            loser.force_disable_check_same_thread = False
            loser.location = tmpdir
            loser.persistent = True
            loser.collections = {}
            loser.aliases = {}
            loser._flock_file = None
            loser._closed = False

            with pytest.raises(Exception) as excinfo:
                loser._load()

            assert "already accessed by another instance" in str(excinfo.value)
            assert loser._flock_file is None
        finally:
            holding.close()
