"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthCheckRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthCheckRequest = HealthCheckRequest

@typing.final
class HealthCheckReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    COMMIT_FIELD_NUMBER: builtins.int
    title: builtins.str
    version: builtins.str
    commit: builtins.str
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        version: builtins.str = ...,
        commit: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_commit", b"_commit", "commit", b"commit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_commit", b"_commit", "commit", b"commit", "title", b"title", "version", b"version"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_commit", b"_commit"]) -> typing.Literal["commit"] | None: ...

global___HealthCheckReply = HealthCheckReply
