"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CreateFullSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___CreateFullSnapshotRequest = CreateFullSnapshotRequest

class ListFullSnapshotsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ListFullSnapshotsRequest = ListFullSnapshotsRequest

class DeleteFullSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SNAPSHOT_NAME_FIELD_NUMBER: builtins.int
    snapshot_name: typing.Text
    """Name of the full snapshot"""

    def __init__(self,
        *,
        snapshot_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["snapshot_name",b"snapshot_name"]) -> None: ...
global___DeleteFullSnapshotRequest = DeleteFullSnapshotRequest

class CreateSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COLLECTION_NAME_FIELD_NUMBER: builtins.int
    collection_name: typing.Text
    """Name of the collection"""

    def __init__(self,
        *,
        collection_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["collection_name",b"collection_name"]) -> None: ...
global___CreateSnapshotRequest = CreateSnapshotRequest

class ListSnapshotsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COLLECTION_NAME_FIELD_NUMBER: builtins.int
    collection_name: typing.Text
    """Name of the collection"""

    def __init__(self,
        *,
        collection_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["collection_name",b"collection_name"]) -> None: ...
global___ListSnapshotsRequest = ListSnapshotsRequest

class DeleteSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COLLECTION_NAME_FIELD_NUMBER: builtins.int
    SNAPSHOT_NAME_FIELD_NUMBER: builtins.int
    collection_name: typing.Text
    """Name of the collection"""

    snapshot_name: typing.Text
    """Name of the collection snapshot"""

    def __init__(self,
        *,
        collection_name: typing.Text = ...,
        snapshot_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["collection_name",b"collection_name","snapshot_name",b"snapshot_name"]) -> None: ...
global___DeleteSnapshotRequest = DeleteSnapshotRequest

class SnapshotDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CREATION_TIME_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    CHECKSUM_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Name of the snapshot"""

    @property
    def creation_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Creation time of the snapshot"""
        pass
    size: builtins.int
    """Size of the snapshot in bytes"""

    checksum: typing.Text
    """SHA256 digest of the snapshot file"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        creation_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        size: builtins.int = ...,
        checksum: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_checksum",b"_checksum","checksum",b"checksum","creation_time",b"creation_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_checksum",b"_checksum","checksum",b"checksum","creation_time",b"creation_time","name",b"name","size",b"size"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_checksum",b"_checksum"]) -> typing.Optional[typing_extensions.Literal["checksum"]]: ...
global___SnapshotDescription = SnapshotDescription

class CreateSnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SNAPSHOT_DESCRIPTION_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    @property
    def snapshot_description(self) -> global___SnapshotDescription: ...
    time: builtins.float
    """Time spent to process"""

    def __init__(self,
        *,
        snapshot_description: typing.Optional[global___SnapshotDescription] = ...,
        time: builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["snapshot_description",b"snapshot_description"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["snapshot_description",b"snapshot_description","time",b"time"]) -> None: ...
global___CreateSnapshotResponse = CreateSnapshotResponse

class ListSnapshotsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SNAPSHOT_DESCRIPTIONS_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    @property
    def snapshot_descriptions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnapshotDescription]: ...
    time: builtins.float
    """Time spent to process"""

    def __init__(self,
        *,
        snapshot_descriptions: typing.Optional[typing.Iterable[global___SnapshotDescription]] = ...,
        time: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["snapshot_descriptions",b"snapshot_descriptions","time",b"time"]) -> None: ...
global___ListSnapshotsResponse = ListSnapshotsResponse

class DeleteSnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIME_FIELD_NUMBER: builtins.int
    time: builtins.float
    """Time spent to process"""

    def __init__(self,
        *,
        time: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["time",b"time"]) -> None: ...
global___DeleteSnapshotResponse = DeleteSnapshotResponse
