from pathlib import Path

CODE_DIR = Path(__file__).parent
ROOT_DIR = CODE_DIR.parent.parent
CLIENT_DIR = ROOT_DIR / "qdrant_client"


AUTOGEN_WARNING_MESSAGE = """
# ******  WARNING: THIS FILE IS AUTOGENERATED  ******
#
# This file is autogenerated. Do not edit it manually.
# To regenerate this file, use
#
# ```
# bash -x tools/generate_async_client.sh
# ```
#
# ******  WARNING: THIS FILE IS AUTOGENERATED  ******

"""
